# Generated by Django 4.2.7 on 2024-05-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_feedback_shop_order_shop_alter_category_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=40),
        ),
    ]
