# Generated by Django 4.2.7 on 2024-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Order Confirmed", "Order Confirmed"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
